name: Deploy
on:
  workflow_dispatch:
jobs:
  Dev_Deploy:
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/aks-deploy.yml@main
    with:
      appName: 'user'
      appEnv: 'dev'
      resourceGroup: 'ukwest-dev'
    secrets:
      vault_token: ${{ secrets.vault_token }}
